spring.application.name: docai
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ics
    username: postgres
    password: postgres
  ai:
    chat:
      provider: ollama
    ollama:
      base-url: http://localhost:11434/
      model: llama3
      chat.options.model: llama3.2
#      embedding.options.model: llama3
    #      init:
#        pull-model-strategy: always
#    chat:
#      provider: openai
#    openai:
#      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch



