spring:
  application:
    name: docai
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ics
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # for dev
    show-sql: true
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          model: qwen2.5:3b
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 10000

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    env:
      enabled: true

info:
  app:
    name: My RAG Application
    version: 1.0.0

app:
  rag:
    reset-on-dimension-drift: true
